[template]
src  = "mpm_prefork.conf.tmpl"
dest = "/etc/apache2/conf.d/mpm.conf"
keys = [
    "/php-apache/prefork/startserver",
    "/php-apache/prefork/minspare",
    "/php-apache/prefork/maxspare",
    "/php-apache/prefork/maxworker",
    "/php-apache/prefork/maxconn",
]
reload_cmd = "/usr/sbin/httpd -k stop && /usr/sbin/httpd -k start -D BACKGROUND"
